// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using yogago.Models;

#nullable disable

namespace yogago.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20250116200158_AddClassAndCartTables")]
    partial class AddClassAndCartTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("C##ASEL")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("yogago.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CARTID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("ADDEDDATE")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<decimal>("ClassID")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CLASSID");

                    b.Property<decimal>("MemberID")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MEMBERID");

                    b.HasKey("CartID")
                        .HasName("PK_CART");

                    b.HasIndex("ClassID");

                    b.HasIndex("MemberID");

                    b.ToTable("CART", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Class", b =>
                {
                    b.Property<decimal>("Classid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CLASSID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Classid"));

                    b.Property<decimal?>("Categoryid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CATEGORYID");

                    b.Property<string>("Classdays")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("CLASSDAYS");

                    b.Property<string>("Classname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("CLASSNAME");

                    b.Property<DateTime>("Classtime")
                        .HasPrecision(6)
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CLASSTIME");

                    b.Property<string>("Imgcover")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("IMGCOVER");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<decimal?>("Trainerid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TRAINERID");

                    b.HasKey("Classid")
                        .HasName("SYS_C008426");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Trainerid");

                    b.ToTable("CLASSES", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Classcategory", b =>
                {
                    b.Property<decimal>("Categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CATEGORYID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Categoryid"));

                    b.Property<string>("Categoryname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("CATEGORYNAME");

                    b.HasKey("Categoryid")
                        .HasName("SYS_C008420");

                    b.ToTable("CLASSCATEGORY", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Classmember", b =>
                {
                    b.Property<decimal>("Classmemberid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CLASSMEMBERID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Classmemberid"));

                    b.Property<decimal?>("Classid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CLASSID");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal?>("Memberid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MEMBERID");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Classmemberid")
                        .HasName("SYS_C008442");

                    b.HasIndex("Classid");

                    b.HasIndex("Memberid");

                    b.ToTable("CLASSMEMBER", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Contactu", b =>
                {
                    b.Property<decimal>("Contactid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CONTACTID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Contactid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("SUBJECT");

                    b.Property<DateTime?>("Submitteddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("SUBMITTEDDATE")
                        .HasDefaultValueSql("SYSDATE\n");

                    b.HasKey("Contactid")
                        .HasName("SYS_C008491");

                    b.ToTable("CONTACTUS", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Discount", b =>
                {
                    b.Property<decimal>("Discountid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("DISCOUNTID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Discountid"));

                    b.Property<string>("Discountcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("DISCOUNTCODE");

                    b.Property<string>("Discountname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("DISCOUNTNAME");

                    b.Property<decimal>("Discountpercentage")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("DISCOUNTPERCENTAGE");

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("DATE")
                        .HasColumnName("ENDDATE");

                    b.Property<string>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ISACTIVE")
                        .HasDefaultValueSql("'Y' ")
                        .IsFixedLength();

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("DATE")
                        .HasColumnName("STARTDATE");

                    b.HasKey("Discountid")
                        .HasName("SYS_C008484");

                    b.HasIndex(new[] { "Discountcode" }, "SYS_C008485")
                        .IsUnique();

                    b.ToTable("DISCOUNT", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Homemanagementimg", b =>
                {
                    b.Property<decimal>("Imgid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("IMGID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Imgid"));

                    b.Property<string>("Imgname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGNAME");

                    b.Property<string>("Imgpath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IMGPATH");

                    b.HasKey("Imgid")
                        .HasName("SYS_C008468");

                    b.ToTable("HOMEMANAGEMENTIMG", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Homemanagementtext", b =>
                {
                    b.Property<decimal>("Textid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("TEXTID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Textid"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("CONTENT");

                    b.Property<string>("Textname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TEXTNAME");

                    b.HasKey("Textid")
                        .HasName("SYS_C008472");

                    b.ToTable("HOMEMANAGEMENTTEXT", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Invoiceinfo", b =>
                {
                    b.Property<decimal>("Invoiceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("INVOICEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Invoiceid"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("Emailsent")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("EMAILSENT")
                        .HasDefaultValueSql("'N' ")
                        .IsFixedLength();

                    b.Property<DateTime?>("Generateddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("GENERATEDDATE")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<decimal?>("Memberplanid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MEMBERPLANID");

                    b.HasKey("Invoiceid")
                        .HasName("SYS_C008458");

                    b.HasIndex("Memberplanid");

                    b.ToTable("INVOICEINFO", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Member", b =>
                {
                    b.Property<decimal>("Memberid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("MEMBERID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Memberid"));

                    b.Property<DateTime?>("Joindate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("JOINDATE")
                        .HasDefaultValueSql("SYSDATE  -- Date the user became a member\n");

                    b.Property<decimal?>("Userid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERID");

                    b.HasKey("Memberid")
                        .HasName("SYS_C008435");

                    b.HasIndex("Userid");

                    b.ToTable("MEMBER", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Memberplan", b =>
                {
                    b.Property<decimal>("Memberplanid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("MEMBERPLANID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Memberplanid"));

                    b.Property<decimal?>("Memberid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MEMBERID");

                    b.Property<decimal?>("Planid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PLANID");

                    b.Property<DateTime?>("Startdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("STARTDATE")
                        .HasDefaultValueSql("SYSDATE\n");

                    b.HasKey("Memberplanid")
                        .HasName("SYS_C008438");

                    b.HasIndex("Memberid");

                    b.HasIndex("Planid");

                    b.ToTable("MEMBERPLAN", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Paymentinfo", b =>
                {
                    b.Property<decimal>("Cardid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("CARDID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Cardid"));

                    b.Property<string>("Cardnumberencrypted")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("CARDNUMBERENCRYPTED");

                    b.Property<DateTime?>("Createddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("CREATEDDATE")
                        .HasDefaultValueSql("SYSDATE -- Timestamp when the record was created\n");

                    b.Property<string>("Cvvencrypted")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("CVVENCRYPTED");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<byte>("Expirymonth")
                        .HasPrecision(2)
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("EXPIRYMONTH");

                    b.Property<byte>("Expiryyear")
                        .HasPrecision(4)
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("EXPIRYYEAR");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<decimal?>("Memberid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MEMBERID");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("ZIPCODE");

                    b.HasKey("Cardid")
                        .HasName("SYS_C008453");

                    b.HasIndex("Memberid");

                    b.ToTable("PAYMENTINFO", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Plan", b =>
                {
                    b.Property<decimal>("Planid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("PLANID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Planid"));

                    b.Property<decimal>("Durationmonths")
                        .HasColumnType("NUMBER")
                        .HasColumnName("DURATIONMONTHS");

                    b.Property<string>("Planname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("PLANNAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("PRICE");

                    b.HasKey("Planid")
                        .HasName("SYS_C008433");

                    b.ToTable("PLAN", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Role", b =>
                {
                    b.Property<decimal>("Roleid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ROLEID");

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("ROLENAME");

                    b.HasKey("Roleid")
                        .HasName("SYS_C008396");

                    b.HasIndex(new[] { "Rolename" }, "SYS_C008397")
                        .IsUnique();

                    b.ToTable("ROLES", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Testimonial", b =>
                {
                    b.Property<decimal>("Testimonialid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("TESTIMONIALID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Testimonialid"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("CONTENT");

                    b.Property<decimal?>("Memberid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MEMBERID");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("NUMBER")
                        .HasColumnName("RATING");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'Pending' ");

                    b.Property<DateTime?>("Submitteddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("SUBMITTEDDATE")
                        .HasDefaultValueSql("SYSDATE                             -- Timestamp of submission\n");

                    b.HasKey("Testimonialid")
                        .HasName("SYS_C008477");

                    b.HasIndex("Memberid");

                    b.ToTable("TESTIMONIAL", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Trainer", b =>
                {
                    b.Property<decimal>("Trainerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("TRAINERID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Trainerid"));

                    b.Property<decimal?>("Experience")
                        .HasColumnType("NUMBER")
                        .HasColumnName("EXPERIENCE");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("SPECIALIZATION");

                    b.Property<decimal?>("Userid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERID");

                    b.HasKey("Trainerid")
                        .HasName("SYS_C008409");

                    b.HasIndex("Userid");

                    b.ToTable("TRAINER", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Userinfo", b =>
                {
                    b.Property<decimal>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Userid"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime?>("Dateadded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("DATEADDED")
                        .HasDefaultValueSql("SYSDATE\n");

                    b.Property<DateTime?>("Dateofbirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DATEOFBIRTH");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Profilepicture")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("PROFILEPICTURE");

                    b.Property<decimal>("Roleid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ROLEID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Userid")
                        .HasName("SYS_C008405");

                    b.HasIndex("Roleid");

                    b.HasIndex(new[] { "Username" }, "SYS_C008406")
                        .IsUnique();

                    b.ToTable("USERINFO", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Userlogin", b =>
                {
                    b.Property<decimal>("Loginid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("LOGINID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Loginid"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("PASSWORD");

                    b.Property<decimal?>("Roleid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ROLEID");

                    b.Property<decimal?>("Userid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("USERID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Loginid")
                        .HasName("SYS_C008414");

                    b.HasIndex("Roleid");

                    b.HasIndex("Userid");

                    b.HasIndex(new[] { "Username" }, "SYS_C008415")
                        .IsUnique();

                    b.ToTable("USERLOGIN", "C##ASEL");
                });

            modelBuilder.Entity("yogago.Models.Cart", b =>
                {
                    b.HasOne("yogago.Models.Class", "Class")
                        .WithMany("Carts")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CART_CLASSES");

                    b.HasOne("yogago.Models.Member", "Member")
                        .WithMany("Carts")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CART_MEMBER");

                    b.Navigation("Class");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("yogago.Models.Class", b =>
                {
                    b.HasOne("yogago.Models.Classcategory", "Category")
                        .WithMany("Classes")
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008427");

                    b.HasOne("yogago.Models.Trainer", "Trainer")
                        .WithMany("Classes")
                        .HasForeignKey("Trainerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008428");

                    b.Navigation("Category");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("yogago.Models.Classmember", b =>
                {
                    b.HasOne("yogago.Models.Class", "Class")
                        .WithMany("Classmembers")
                        .HasForeignKey("Classid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008443");

                    b.HasOne("yogago.Models.Member", "Member")
                        .WithMany("Classmembers")
                        .HasForeignKey("Memberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008444");

                    b.Navigation("Class");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("yogago.Models.Invoiceinfo", b =>
                {
                    b.HasOne("yogago.Models.Memberplan", "Memberplan")
                        .WithMany("Invoiceinfos")
                        .HasForeignKey("Memberplanid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008459");

                    b.Navigation("Memberplan");
                });

            modelBuilder.Entity("yogago.Models.Member", b =>
                {
                    b.HasOne("yogago.Models.Userinfo", "User")
                        .WithMany("Members")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008436");

                    b.Navigation("User");
                });

            modelBuilder.Entity("yogago.Models.Memberplan", b =>
                {
                    b.HasOne("yogago.Models.Member", "Member")
                        .WithMany("Memberplans")
                        .HasForeignKey("Memberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008439");

                    b.HasOne("yogago.Models.Plan", "Plan")
                        .WithMany("Memberplans")
                        .HasForeignKey("Planid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008440");

                    b.Navigation("Member");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("yogago.Models.Paymentinfo", b =>
                {
                    b.HasOne("yogago.Models.Member", "Member")
                        .WithMany("Paymentinfos")
                        .HasForeignKey("Memberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008454");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("yogago.Models.Testimonial", b =>
                {
                    b.HasOne("yogago.Models.Member", "Member")
                        .WithMany("Testimonials")
                        .HasForeignKey("Memberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008478");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("yogago.Models.Trainer", b =>
                {
                    b.HasOne("yogago.Models.Userinfo", "User")
                        .WithMany("Trainers")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008410");

                    b.Navigation("User");
                });

            modelBuilder.Entity("yogago.Models.Userinfo", b =>
                {
                    b.HasOne("yogago.Models.Role", "Role")
                        .WithMany("Userinfos")
                        .HasForeignKey("Roleid")
                        .IsRequired()
                        .HasConstraintName("SYS_C008407");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("yogago.Models.Userlogin", b =>
                {
                    b.HasOne("yogago.Models.Role", "Role")
                        .WithMany("Userlogins")
                        .HasForeignKey("Roleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008417");

                    b.HasOne("yogago.Models.Userinfo", "User")
                        .WithMany("Userlogins")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SYS_C008416");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("yogago.Models.Class", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Classmembers");
                });

            modelBuilder.Entity("yogago.Models.Classcategory", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("yogago.Models.Member", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Classmembers");

                    b.Navigation("Memberplans");

                    b.Navigation("Paymentinfos");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("yogago.Models.Memberplan", b =>
                {
                    b.Navigation("Invoiceinfos");
                });

            modelBuilder.Entity("yogago.Models.Plan", b =>
                {
                    b.Navigation("Memberplans");
                });

            modelBuilder.Entity("yogago.Models.Role", b =>
                {
                    b.Navigation("Userinfos");

                    b.Navigation("Userlogins");
                });

            modelBuilder.Entity("yogago.Models.Trainer", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("yogago.Models.Userinfo", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Trainers");

                    b.Navigation("Userlogins");
                });
#pragma warning restore 612, 618
        }
    }
}
